Ignore result of builpacks-detect.
A buildpack configured inside .cfbuildpacks shall be installed even if no Framework was detected.

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -46,23 +46,25 @@ for BUILDPACK in $(cat $1/.cfbuildpacks); do
     chmod -f +x $dir/bin/{detect,compile,release} || true
 
     framework=$($dir/bin/detect $1)
-
     if [ $? == 0 ]; then
       echo "=====> Detected Framework: $framework"
-      $dir/bin/compile $1 $2 $3
+    else
+      echo "=====> Detection failed - ignoring result"
+    fi
+    
+    $dir/bin/compile $1 $2 $3
 
-      if [ $? != 0 ]; then
-        exit 1
-      fi
+    if [ $? != 0 ]; then
+      exit 1
+    fi
 
-      # check if the buildpack left behind an environment for subsequent ones
-      if [ -e $dir/export ]; then
-        source $dir/export
-      fi
+    # check if the buildpack left behind an environment for subsequent ones
+    if [ -e $dir/export ]; then
+      source $dir/export
+    fi
 
-      if [ -x $dir/bin/release ]; then
-        $dir/bin/release $1 > $1/last_pack_release.out
-      fi
+    if [ -x $dir/bin/release ]; then
+      $dir/bin/release $1 > $1/last_pack_release.out
     fi
   fi
 done
